<strong>Web Design I</strong>
<blockquote>This course teaches students how to use HTML and CSS to create intuitive Website interfaces and layouts, based upon universally accepted user-centered design principles. Emphasis is on developing good visual design skills using HTML and CSS as the primary tools.</blockquote>
<strong>Digital Art, Illustration and Design I</strong>
<blockquote>This course focuses on industry-standard software, specifically Adobe Photoshop and Illustrator, to teach students how to create layouts, graphics and illustrative elements for integrated media projects. Emphasis is on producing graphic elements for Websites, applications, as well as assets for video production, motion graphics and animations.</blockquote>
<strong>Photography for integrated media</strong>
<blockquote>This course covers the basic principles of photography in a digital environment. Students consider both the technical and visual components of the photograph in critical discussions with their instructor and their peers. This course introduces the use of digital single lens reflex (DSLR) cameras as well as basic editing and printing techniques. The cameras used require the student to manually adjust shutter speed and aperture.</blockquote>
<strong>Typography and Colour Theory for Integrated media</strong>
<blockquote>This course introduces the art and science of typography and digital colour theory. Students make strategic colour choices and craft well-designed typographic layouts for use in a variety of integrated media projects. They learn the basic principles of typography as they apply to meaning, legibility and information hierarchy. Students also explore the social, emotive and symbolic aspects of colour.</blockquote>
<strong>Communications for Integrated media</strong>
<blockquote>This course focuses on effective sentence and paragraph writing. Through visual analysis and comprehension exercises students learn the essential elements of composition and the fundamental principles of written communication. Activities will incorporate in-class discussions/applications employing proper word usage, grammar and punctuation, research tasks, short writing assignments, proofreading exercises, and peer assessments.</blockquote>
<strong>Gen Ed - Social Media</strong>
<blockquote>This course explores the history, current developments and potential future advances in social media and associated technologies. Students critically examine the impact of social media on society and examine what, if any, effect social media has had on existing systems and models of communication.</blockquote>